version: 0.0
os: linux

files:
  - source: target/webgoat-2023.8-SNAPSHOT.jar
    destination: /app
    overwrite: yes

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300

  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300

  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300

  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
