version: 0.2

phases:
    install:    
        runtime-versions:
            java: corretto17
    pre_build:
        commands:
            - echo "Pre-build phase starting...."
    build:
        commands:
            - echo "Build started on `date`"
            - ./mvnw clean install -D skipTests
    post_build:
        commands:
            - echo "Build completed on `date`"
            
artifacts:
    files:
        - target/webgoat-2023.9-SNAPSHOT.jar
        - appspec.yml
        - start.sh
