version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17  
    commands:
      - echo "Install phase: Installing Maven dependencies..."
      - mvn install
  pre_build:
    commands:
      - echo "Pre-build phase starting..."
  build:
    commands:
      - echo "Build phase: Generating JAR file with Maven..."
      - mvn package
  post_build:
    commands:
      - echo "Build completed at: `date`"

artifacts:
  files:
    - target/webgoat-*.jar
    - appspec.yml
    - scripts/**
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'
